name:                gradle-loop
version:             0.1.0.0
github:              "davecturner/gradle-loop"
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2018 David Turner"

description:         Please see the README on GitHub at <https://github.com/davecturner/gradle-loop#readme>

dependencies:
- base >= 4.7 && < 5
- conduit
- conduit-extra
- resourcet
- time
- bytestring
- iso8601-time
- directory
- wreq
- text
- aeson

ghc-options: -Wall -Werror

executables:
  gradle-loop:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
